name: Update data

on:
  schedule:
    - cron: "* * * * *"  # Runs daily at midnight UTC. Adjust as needed.
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true  # Use public RStudio Package Manager for faster package installation
          install-r: true  # Install the latest version of R available

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("DBI", "odbc", "dplyr", "crypto2"))'

      - name: Run R script
        run: |
          Rscript TimeTest.R
