name: Update data

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute for testing. Adjust to your desired schedule.
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true  # Use public RStudio Package Manager for faster package installation
          install-r: true  # Install the latest version of R available

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("DBI", "odbc", "dplyr", "crypto2"))'

      - name: Run R script
        run: |
          Rscript -e 'source("TimeTest.R")'

      - name: Retry if failed
        if: ${{ failure() }}
        run: |
          echo "Retry the installation"
          sleep 10  # Wait for 10 seconds before retrying
          Rscript -e 'install.packages(c("DBI", "odbc", "dplyr", "crypto2"))'

      - name: Final run of R script
        run: |
          Rscript -e 'source("TimeTest.R")'
